### ISSUE TITLE
Uploading small images

### ISSUE THREAD

**Issue by margareti** [scottcheng/cropit#102]
Hello! Great plugin! 
However, I noticed that it doesn't upload images smaller than 100 KB (this is seen on the live demo as well).
Is there a way around this?

**Comment by BugHunter2k** [comment]
Cropit does reject small images by default, you can change this behavior by using the smallImage-Option (see: http://scottcheng.github.io/cropit/#docs-options-smallImage)

Example:
```javascript
$('#image-cropper').cropit({
  smallImage: 'allow'
});
```

**Comment by scottcheng** [comment]
Thanks @BugHunter2k. I've added a small image error message on the demo so it doesn't fail silently when image is too small.

**Comment by jonjie0317** [comment]
Hi @BugHunter2k . Thanks for the info, but now, I cannot zoom it in. Why is that?
