### ISSUE TITLE
Image seriously degraded with Cropit

### ISSUE THREAD

**Issue by PavSidhu** [scottcheng/cropit#104]
By setting the preview area to 300px by 300px, the image is converted into that size, and then in my case converted to base64 and uploaded.

By setting the preview area to that value, the image size changes which for some reason degrades the image a lot, making it appear almost blurry.

Is there a way to retain the image quality even though the image is resized?

**Comment by scottcheng** [comment]
Do you mind sharing the image that you are having problem with?

**Comment by PavSidhu** [comment]
I used several images, some .png and some .jpg but here is an example:
![wp_encrusted_vi-2560x1440_00000](https://cloud.githubusercontent.com/assets/4911505/9836312/ed7fe69a-5a0c-11e5-8267-f25ef33c4516.jpg)

I believe part of the issue is that I set the preview size to be 200px by 200px so I could fit it into the page though I would like to be saved as 300px by 300px.

I tested this issue by capturing the base64 export and converting it back to an image though it still appears blurry.

**Comment by scottcheng** [comment]
Since you are trying to export to 300x300 from a 200x200 preview box, have you tried setting [`exportZoom`](http://scottcheng.github.io/cropit/#docs-options-exportZoom) as 1.5? This is the image I got with 200x200 preview size and 1.5 exportZoom:

![download](https://cloud.githubusercontent.com/assets/1612169/9838296/106a1e6c-5a28-11e5-9044-3e0d6fe31966.png)

**Comment by PavSidhu** [comment]
I'll give that a try thanks. However can you still see the image has lost some of it's quality? It looks blurry compared to the original?

**Comment by scottcheng** [comment]
Yes it does look more blurry than the original. Image resizing can be tricky and there's only so much we can do with canvas. There are [libraries](http://nodeca.github.io/pica/demo/) and [discussions](http://stackoverflow.com/questions/18922880/html5-canvas-resize-downscale-image-high-quality) around this, and we might be able to improve the resizing quality with more complicated mechanisms.

**Comment by oscargglez** [comment]
Hi, the only way for me to fix this problem was using the option "originalSize: true". then I got the image size as follow...

var imageData = $('#croper-imagen').cropit('export', {
			type: 'image/jpeg',
			originalSize: true,
			quality: 0.5
		});
var image = new Image();
		image.onload = function(){
		 	$("#crop-imagen #w").val(image.width);
		 	$("#crop-imagen #h").val(image.height);
}
image.src = imageData;

...and at last on the php file do the operations need to crop and create the "new" image, something like that:
imagecopyresampled($truecolor,$imgSrc,0,0,0,0,$myWith,$myHeight,$_POST["w"],$_POST["h"]);

And the final image quality its ok.

Sorry for my english and code (not a pro) and I hope this help you or give you some inspiration :-).

**Comment by scottcheng** [comment]
@oscargglez That's a good solution, especially if you want to keep the original image e.g. for editing cropping in the future.

**Comment by PavSidhu** [comment]
Is there a solution which works for python?

**Comment by scottcheng** [comment]
If you do it on the server you'd have a wide range of options, e.g. [ImageMagick](http://www.imagemagick.org/script/index.php).

**Comment by nunoguerra** [comment]
Any suggestion to make it better?

Crop image preview is perfect:
http://dev.nunoguerra.com/dropbox/uploads/preview.png

But the final crop image is bad:
http://dev.nunoguerra.com/dropbox/uploads/final.jpg

PHP code that I use to save data in file:

$open_file = fopen($cover, 'wb');
$data = explode(',', $_POST['cover']);
fwrite($open_file, base64_decode($data[1]));
fclose($open_file);

**Comment by PavSidhu** [comment]
I used a Python web framwork not PHP but the way I fixed this issue was by getting the crop coordinates from https://github.com/scottcheng/cropit/issues/45 and cropping the original uploaded image with a Python library. I'm sure you could find an alternative for PHP.

**Comment by nunoguerra** [comment]
I don't have possibility to generate the image on the server.

So I want to find a way to get crop image by the client side, Cropit is good but I want better quality in the final image...

**Comment by scottcheng** [comment]
@nunoguerra One way to generate high-quality resized images is by combining cropit with another image-resizing library like [Pica](http://nodeca.github.io/pica/demo/). You can use cropit as a UI component for cropping, take coordinates from cropit and draw it on a new canvas, and then use Pica to actually do the resizing.

**Comment by luka5** [comment]
Today I stumbled over the same issue.
In my case I dont want to scale the image, I just need the correct ratio.
Meaning, if the original image has a resolution of 1000 x 1000 and the preview size is 100 x 50, I want to get a result in the resolution of 1000 x 500.
We can reach this by setting the `exportZoom` value dynamically depending on the image and preview width.

      var $form = $('...');
      var exportZoom = 1;
      var imageSize = $form.cropit('imageSize');
      var previewSize = $form.cropit('previewSize');
      if (imageSize.width > previewSize.width) {
        exportZoom = Math.round(imageSize.width/previewSize.width, 2);
      }
      $form.cropit('exportZoom', exportZoom);


Since modern browsers can scale down images quite good, this fixes my issue.
@PavSidhu  does this work for you?

**Comment by PavSidhu** [comment]
Thanks @luka5, I haven't tried your solution but it seems like it should work well. The way I managed this was by getting the coordinates of the crop with [this method](https://github.com/scottcheng/cropit/issues/119 ) in this issue and then uploading the original image to the server where it is cropped. As my server uses python I used the PIL library to crop and save the image however if anyone is using another language, I'm sure there should be other alternatives.

**Comment by DevotionGeo** [comment]
@scottcheng can we get a jpg output from pica?

**Comment by scottcheng** [comment]
@DevotionGeo not sure if you've seen this but I created a demo that combined cropit and pica. To your first question, yes you can because pica would draw the resized image on another canvas and you can export it to whatever format you need.

**Comment by DevotionGeo** [comment]
Yeah, I sorted it out. 
One more question. Because I didn't read all the source code for Pica I don't know what is used under the hood and if Pica is also supported on the browsers which support canvas?

**Comment by DevotionGeo** [comment]
@scottcheng I'm trying to send data created by pica to a php file to show it on the page, when I do it the normal canvas way, it works, but when i try to do it through pica it doesn't work, following is the code for both the cases.

1. The following code implements it through normal canvas and it works.

``` 
<form action="http://localhost/img_upload/image/upload" id="input-form" method="post" accept-charset="utf-8">
    <div class="image-editor">
        <input type="file" class="cropit-image-input">
        <div class="cropit-image-preview"></div>
        <div class="image-size-label">
          Drag Slider to Resize
        </div>
        <input type="range" class="cropit-image-zoom-input">
        <input type="hidden" name="image-data" class="hidden-image-data" />
        <button type="submit">Submit</button>
      </div>
</form>


<script>
  $(function() {
    $('.image-editor').cropit();

    $('#input-form').submit(function() {

      // Move cropped image data to hidden input
      var imageData = $('.image-editor').cropit('export', {type: 'image/jpeg',quality: .75});
      $('.hidden-image-data').val(imageData);

      // don't submit the form if the imageData is empty
      // for example if user is clicking on the submit without loading an image
      if (imageData == null) {
        return false;
      }
    });
  });
</script>
```


2. The following code tries to implement it through pica and fails.

```
<form action="http://localhost/img_upload/image/upload" id="input-form" method="post" accept-charset="utf-8">
    <div class="image-editor">
      <input type="file" class="cropit-image-input">
      <div class="cropit-image-preview"></div>
      <div class="image-size-label">
        Drag slider to zoom
      </div>
      <input type="range" class="cropit-image-zoom-input">
      <input type="hidden" name="image-data" class="hidden-image-data">
      <input type="submit" value="Upload">
    </div>
</form>


<script>
  $(document).ready(function() {
    var $editor = $('.image-editor');
    $editor.cropit();

    $('#input-form').submit(function() {
      // Get cropping information
      var imgSrc = $editor.cropit('imageSrc');
      var offset = $editor.cropit('offset');
      var zoom = $editor.cropit('zoom');
      var previewSize = $editor.cropit('previewSize');
      var exportZoom = $editor.cropit('exportZoom');

      var img = new Image();
      img.src = imgSrc;

      // Draw image in original size on a canvas
      var originalCanvas = document.createElement('canvas');
      originalCanvas.width = previewSize.width / zoom;
      originalCanvas.height = previewSize.height / zoom;
      var ctx = originalCanvas.getContext('2d');
      ctx.drawImage(img, offset.x / zoom, offset.y / zoom);

      // Use pica to resize image and paint on destination canvas
      var zoomedCanvas = document.createElement('canvas');
      zoomedCanvas.width = previewSize.width * exportZoom;
      zoomedCanvas.height = previewSize.height * exportZoom;
      pica.resizeCanvas(originalCanvas, zoomedCanvas, {
        // Pica options, see https://github.com/nodeca/pica
        
        
      }, function(err) {
        if (err) { return console.log(err); }

        // Resizing completed
        // Read resized image data
        var picaImageData = zoomedCanvas.toDataURL('image/jpeg', .75);
        $('.hidden-image-data').val(picaImageData);

      });

      if (picaImageData == null) {
        return false;
      }

    });
  });
</script>
```

I don't know where is the problem in the code. Please help me. Thank You.
