### ISSUE TITLE
Demo doesn't work with jpgs

### ISSUE THREAD

**Issue by mrchief** [scottcheng/cropit#105]
Does it only work with pngs? I uploaded several jpgs and none of them loaded in the preview. No errors in console but the preview simply doesn't work.

**Comment by scottcheng** [comment]
It should work jpgs. The reason you think it's not working is probably because the image is too small. I've added a error message on the [demo](http://scottcheng.github.io/cropit/) so it doesn't fail silently. Let me know how that works for you.

**Comment by mrchief** [comment]
Yeah I see the error now. Is there a specific reason for this check? Most avatars will not be as big so this check could be limiting in those scenarios.

**Comment by scottcheng** [comment]
By default cropit requires images that are larger than the preview area os it won't be stretched. This is to ensure cropped image quality. For avatars your required size would also be relatively small. If you want to allow smaller images, there is a [`smallImage` option](http://scottcheng.github.io/cropit/#docs-options-smallImage).
