### ISSUE TITLE
Bypass Upload

### ISSUE THREAD

**Issue by difster** [scottcheng/cropit#107]
I want to combine this with an image gallery so that a user can choose from a catalog of images and then make that image available to cropit for resizing, cropping, etc.

So let's say I have an image already on my page. For the sake of simplicity, let's just say it's a single image. If I click that I want it to load in cropit in place of actually uploading an image from a folder on my computer.

If you could point me in the right direction for doing that, I would very much appreciate it.

**Comment by scottcheng** [comment]
You can setting `imageSrc` programmatically like this:

```js
$imageCropper.cropit('imageSrc', 'http://placekitten.com/g/1280/800');
```

**Comment by difster** [comment]
Ahhhh I was *SO* close. I had tried exactly that in the image-preview, but not in the main cropit div.

Thank you very much for the answer.
