### ISSUE TITLE
Gif Export Issue

### ISSUE THREAD

**Issue by akvlko** [scottcheng/cropit#108]
I am using cropit for one of my project, it works like charm for all image types but in case of GIF $image.cropit('export', {type: 'image/gif',	originalSize: true}) giving only the first frame of Animated GIF images. Is there any way I can export the full animated GIF as its being seen in canvas?

**Comment by scottcheng** [comment]
Cropit takes a "snapshot" of the image on the canvas, so unfortunately it cannot support animated GIFs. However I'm imagining there should be server-side libraries to do that job, and perhaps you can send cropping data (offset, zoom) along with the original image to the server and do the cropping there.
