### ISSUE TITLE
Can't get this to work in Safari on MAC

### ISSUE THREAD

**Issue by DSheed** [scottcheng/cropit#110]
Hello,

Firstly I would like to say thank you, this is an amazing package and I managed to get it to work straight away in IE and Chrome, the problem I am having is on the MAC. When I select a picture and click export it doesn't upload to my server. Instead I get a blank (plain white) image in my server folder. I'm not sure what I am doing wrong. I am fairly new to PHP and coding etc. so I am probably missing something simple. I have checked some other posts and I noticed that some people mentioned "FileReader" not available on MACs. I was just wondering if you have a quick fix for my problem - thanks

**Comment by scottcheng** [comment]
Based on what you described, the most likely reason is a bug that we had with Safari which produces empty images. Try updating cropit to 0.4.5 and it should fix the problem.
