### ISSUE TITLE
Calculate actual crop info

### ISSUE THREAD

**Issue by williansebastiao** [scottcheng/cropit#111]
Is there any way to retrieve the x and y coordinates? The width and height would also be possible? I'm trying to make a cut but I am not succeeding.

**Comment by scottcheng** [comment]
Yes. Check out the `offset`, `zoom`, and `previewSize` (or `imageSize`, depending on what you are looking for) APIs -- docs [here](http://scottcheng.github.io/cropit/#docs-apis).

**Comment by williansebastiao** [comment]
I looked at the api though, when you cut, the picture is not correct. Already try to offset; previewSize and zoom but no use.
it is as if the coordinates were lost

**Comment by williansebastiao** [comment]
I looked at the api though, when you cut, the picture is not correct. Already try to offset; previewSize and zoom but no use.
it is as if the coordinates were lost

**Comment by scottcheng** [comment]
The offset that the API returns is offset of the image w.r.t. the crop box. From what you described you seem to be looking for the coordinates of the cropbox w.r.t. the image, which would be (offset.x / zoom, offset.y / zoom).
