### ISSUE TITLE
Exporting canvas image from external origin doesn't work in IE

### ISSUE THREAD

**Issue by aas395** [scottcheng/cropit#120]
Hi,

I'm noticing that I can't export images from the canvas if they're from another domain in IE (back to 9, as far as I can tell). Those browsers don't do CORS well (if at all) so they need their own method for getting images from other domains.

Here's the error I get: 

SCRIPT5022: SecurityError
File: jquery.cropit.js, Line: 675, Column: 8

I dug around a bit and came up with this as the method that should be used to get these images in IE: http://stackoverflow.com/questions/16956295/ie10-and-cross-origin-resource-sharing-cors-issues-with-image-canvas

Still working on fixing this in my local copy but seems promising.

**Comment by scottcheng** [comment]
Closed in f6eb24f9030f93c5e73413bd87f7b876d4c66b9e.
