### ISSUE TITLE
need to zoom out a large image, until it fit to preview container

### ISSUE THREAD

**Issue by cpagit** [scottcheng/cropit#127]
Hi!
There are surely some options I'm missing...  I have a large image (height of 1570px and width of 1324px), which initially is partially displayed in the preview container (it's ok, it's what I want) and the slider is initially set at its middle position approximately.  From there, I want to zoom out until the width fits in the preview container (180px).  I'm able to do that, but the quality is not good enough.  Note that this is not an export problem, just a preview problem.  Thanks for advice!

My options are currently:

$(function() {
    $('.image-editor').cropit({
        minZoom: 'fill',
        maxZoom: 3,
        initialZoom: 'image',
        smallImage: 'allow',
        imageBackground: true,
        imageBackgroundBorderWidth: 20,
        imageState: {
        src: ' [ ... a large image ] ',
        },
    });

```
var zoomSlider = $('.image-editor').find('input.cropit-image-zoom-input');
zoomSlider.attr({ min: 0, max: 1, step: 0.01 });
```

});

And css contains:
      .cropit-image-preview {
        background-color: #f8f8f8;
        background-size: cover;
        border: 5px solid #ccc;
        border-radius: 3px;
        margin-top: 7px;
        width: 180px;
        height: 213px;
        cursor: move;
      }

![cropit_example](https://cloud.githubusercontent.com/assets/15466343/11099265/641d0c12-8878-11e5-9aca-8bca07fa2285.png)

**Comment by denis1222223** [comment]
thanks a lot

**Comment by rakeshaspl** [comment]
Just change this option.

      minZoom:'fit',

**Comment by rakeshaspl** [comment]
For quality, you can set by set of this options.

$imageCropper.cropit('export', {
  type: 'image/jpeg',
  quality: 0.9,
});

**Comment by cpagit** [comment]
Thanks, may be it will help someone else.  I reported this problem 2 years ago and finally, I decided to use "Cropper" instead of "Cropit". 
See https://github.com/fengyuanchen/cropper.
I close this issue.
