### ISSUE TITLE
How to set multiple preview divs?

### ISSUE THREAD

**Issue by Manmade** [scottcheng/cropit#138]
Does anybody know how to set so you can have a different preview class?
So I can have something like this:
$('.image-editor').cropit({
          preview:$(".cropit-image-preview")
       });
$('.image-editor2').cropit({
          preview:$(".cropit-image-preview2")
       });
As it is now it always shows the image in .cropit-image-preview and I need to be able to set the second one to show the image in cropit-image-preview2.
I really need to get this working, thanks :-)

**Comment by sidaurukfreddy** [comment]
You should make each css and js also

**Comment by sidaurukfreddy** [comment]
ah i got thiss issue too, already make multiple css but nothing working, i'm focus on cropit-image-preview too, where is the author lah

**Comment by sidaurukfreddy** [comment]
Hello i have been solved this issue, hope someone found this lah ya !
first of all , this   class is main   <pre>cropit-image-preview</pre>
for all crop and resize so you will success using multiple images preview, so i did hacky the plugin then please open your jquery.cropit.js and search it class cropit-image-preview line 927 then i copy become 2 files then change the one as like what i want

for example this is my html 
<pre>
<div class="cropit-image-preview-users">
                    <div class="error-msg"></div>
                </div>
</pre>
then copy your  js and rename up to you  then goes to lin2 926 then change it 
<pre>
	  PREVIEW: 'cropit-image-preview-users', //change based on your div
</pre>


Thanks

**Comment by sidaurukfreddy** [comment]
Shit happend to me, all working fine but validations errors not working, where is the author lah

**Comment by HardikPatel88** [comment]
Hello sidaurukfreddy,

I have tryed as you said but not working .
please send me demo if you have .
my mail id : hardik.patel@imobdevtech.com

thanks in advance

**Comment by Manmade** [comment]
Hi sidaurukfreddy, did you get this to work? And how? Do you have a demo? Thanks :-)

**Comment by scottcheng** [comment]
To the original question, the option to change preview element is `$preview`, not `preview`. Please refer to the doc <http://scottcheng.github.io/cropit/#docs-options-preview>

**Comment by nithingm1** [comment]
Hi, i have another question how to upload multiple image to the same image-preview-div . ? Please look at this question https://github.com/scottcheng/cropit/issues/212
