### ISSUE TITLE
Maximum zoom level more than 100%

### ISSUE THREAD

**Issue by vlatka-sinisa** [scottcheng/cropit#15]
As we understood currently maximum zoom level is "100%" (original image size). 

Is it possible that the maximal allowed zoom level would be greater than 100% (e.g. 200% or even 500%)?
That way user can crop just a small fragment even if the source image is exactly the size of "required image" or smaller that required size.

Currently if the user uploads image that is smaller than requested size, zoom options are disabled and the picture is resized so that it fits requirements (what is great), but the user can move (crop) required part (but not zoom it further).

I understand that the picture would be resampled in browser and that it wouldn't look as good thats why it would be good if it is possible to be added as an option (that picture would be useful to us even when resampled from lower resolution).

**Comment by phunksta** [comment]
I would like to also like to add to this request, but in my case the zoom is restrictive when the user wishes to 'letterbox' an image i.e. choose an area including some additional white/black areas when the zoom cannot be set below 1x.
It would be OK to limit by the larger dimension.
Is it possible for me to adjust the code so that the far-left of the slider fits the larger dimension into the box, even if the other dimension has to be 'letterboxed' to allow this?

**Comment by scottcheng** [comment]
@phunksta sorry but I'm having a hard time trying to understand what you need. What exactly do you mean by "letterboxing"? Have you tried `fitWidth`/`fitHeight`?

**Comment by phunksta** [comment]
Hi,

Many thanks for coming back to me. They say a picture is worth 1000 words, probably a million badly written ones!

Please see attached for an illustration of my problem. To allow the user to shrink this logo into the crop box, they would need to be able to zoom until the width fit within the crop box, making the resulting height less than the crop box height.

I’d like to allow this, filling the resulting ‘new’ area with white.

Do you think this is possible? Where would I tweak?

Thanks,
Phil (@phunksta)

**Comment by scottcheng** [comment]
Hi @phunksta, sorry I can't see the image attachment (seems like github took it out), but from what you said it seems like `fitWidth` and/or `fitHeight` could be the solution. These options are not documented. For example, if you want the user to be able to zoom out until the image width fits the container width even if the height goes smaller than the container height, you can pass in `fitWidth: true` when initializing cropit. Let me know how it works for you!

**Comment by phunksta** [comment]
This sounds like exactly what I'm looking for! I'll give it a try.


Sent from Samsung Mobile

-------- Original message --------

**Comment by phunksta** [comment]
Hi,

Thanks for the fitWidth and fitHeight settings. They do help, but once ‘fit’ the user can’t seem to move the image around any longer - it seems to stick to the top-left.

As github is killing off the attachments, I’ve popped some examples for you here: http://www.filedropper.com/cropitexamples <http://www.filedropper.com/cropitexamples>

I’ve taken both ‘too wide’ and ‘too tall’ examples and tried with default settings, then with fitWidth applied, then finally with fitHeight applied. I didn’t quite get if these could only be applied one at a time I admit I didn’t try together! 

I guess I’m looking for something like pseudo-code:

1) Take the ‘cropit’ area aspect ratio. e.g 4:3, so horizontal is larger dimension.
2) Check the uploaded file aspect ratio
  a) if horizontal is larger than cropit dimension (e.g. 16:9) , then fitWidth. 
  b) if vertical is larger than crept dimension (e.g. 3:5) then fitHeight.
3) if fitWidth or fitHeight, then allow user to move image into centre of either dimension

Thanks again for reading!


> On 25 Jan 2015, at 22:20, Scott Cheng <notifications@github.com> wrote:
> 
> Hi @phunksta <https://github.com/phunksta>, sorry I can't see the image attachment (seems like github took it out), but from what you said it seems like fitWidth and/or fitHeight could be the solution. These options are not documented. For example, if you want the user to be able to zoom out until the image width fits the container width even if the height goes smaller than the container height, you can pass in fitWidth: true when initializing cropit. Let me know how it works for you!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/scottcheng/cropit/issues/15#issuecomment-71396817>.
> 

Black Rose Solutions Limited is a company registered 
in England and Wales, Registered number: 6136400
Registered Office: 74 Leacroft Road, Penkridge, 
Staffordshire  ST19 5BU
This message is private and confidential. If you have
received it in error please notify us and remove it from
your system.

**Comment by scottcheng** [comment]
Hi @phunksta -- sorry for the late reply. I think what you proposed could work, especially with the [`fillBg` option](https://github.com/scottcheng/cropit/blob/f1978449be55f977cec312357b076d140fbbe82e/src/cropit.coffee#L337). I'll give it a shot this week and I'll let you know how it goes.

**Comment by phunksta** [comment]
Cheers, I can see stuff is going on so wasn’t pushing for an update ;)

I grabbed 0.2.0 the other day and tried out ‘freeMove’. This works nicely and solves the ‘stuck to top-left’ issue.

I can see some new stuff going in for dimensions too, so rubbing hands in anticipation!

Thanks,
Phil

> On 2 Feb 2015, at 21:43, Scott Cheng <notifications@github.com> wrote:
> 
> Hi @phunksta <https://github.com/phunksta> -- sorry for the late reply. I think what you proposed could work, especially with the fillBg option <https://github.com/scottcheng/cropit/blob/f1978449be55f977cec312357b076d140fbbe82e/src/cropit.coffee#L337>. I'll give it a shot this week and I'll let you know how it goes.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/scottcheng/cropit/issues/15#issuecomment-72544212>.
> 

Black Rose Solutions Limited is a company registered 
in England and Wales, Registered number: 6136400
Registered Office: 74 Leacroft Road, Penkridge, 
Staffordshire  ST19 5BU
This message is private and confidential. If you have
received it in error please notify us and remove it from
your system.

**Comment by hberberoglu** [comment]
I also need that "overzoom" feature and I agree with @vlatka-sinisa.

@scottcheng; thanks for this great plugin.

**Comment by bionik** [comment]
I would also be interested in option to enable overzooming. Thanks! Great plugin!

**Comment by rmxakalogistik** [comment]
Hello i need also overzooming. thanks! you for this work
