### ISSUE TITLE
how to rotate image

### ISSUE THREAD

**Issue by maheshweboners** [scottcheng/cropit#150]
this image cropt code really nice but how to rotate image any solution plz ..

**Comment by jacondaloas** [comment]
cropit is not able to turn

**Comment by HardikPatel88** [comment]
How to get base64 of rotated image.

**Comment by pensierinmusica** [comment]
Relates to #92

**Comment by scottcheng** [comment]
Closed in d06fa78e3e789452675295de6aee7a08c4ade0b6.

**Comment by cercao** [comment]
I saw in documentation this:
 "If, after rotated by 90 degrees, the dimension of the image no longer meets the requirements, it would be rotated by 180 degrees."

Is there any way to just rotate 90 degree and keep like this ?

thks
