### ISSUE TITLE
Preloading image on chrome gives CORS error on Chrome when console is closed!

### ISSUE THREAD

**Issue by hossein761** [scottcheng/cropit#151]
Hi,
We are trying to preload the cropper with a remote image but this only works when the debug console is open on Chrome! As soon as we close it, it won't work. Could you please double check this? Thanks!

**Comment by ngouy** [comment]
Kinda same here. But it doesn't works at all, console or not, using chrome or firefox, and using allowCrossOrigin: true in my query

**Comment by scottcheng** [comment]
Closed in f6eb24f9030f93c5e73413bd87f7b876d4c66b9e.
