### ISSUE TITLE
Symfony2 and VichUploaderBundle integration

### ISSUE THREAD

**Issue by xmon** [scottcheng/cropit#155]
Hi,

In one of my projects I needed to integrate Cropit in Symfony2.

I found there was nowhere to see how, so I solved [this integration on Stackoverflow](http://stackoverflow.com/questions/33973022/symfony2-cropit-how-to-get-back-my-cropped-image/35095970#35095970), I'd like to share for anyone who may need it.

Cheers

**Comment by scottcheng** [comment]
Thanks for sharing. Closing this non-issue and people can still find it by searching.
