### ISSUE TITLE
How to set particular height and width for the image-preview

### ISSUE THREAD

**Issue by divyamovva** [scottcheng/cropit#156]
I have to set the dynamic height and width but the background container to be fixed.For example i have the 32x32 px image i have to show that particular part to be highlighted in that particularimage.I used imagebackgroundborderwidth as an array[10,10,10,10] .how to set the image background both horizantally and vertically

**Comment by scottcheng** [comment]
That sounds tricky. One way is to have another container, which has fixed size, that wraps cropit preview container, and set that outer container to `overflow: hidden`. I don't think we should build this feature into cropit.
