### ISSUE TITLE
Cancel select new image

### ISSUE THREAD

**Issue by mdcsfk** [scottcheng/cropit#158]
If I click 'select new image', the previous one is disappearing. So, if i will cancel image upload, i will see an empty space instead of previously uploaded image. Why the previous image being removed and how do i put it back?

UPDATE: sorry, my bad:
```
.cropit({
			imageState: { 
				src: this.props.image,
				imageBackground: true,
			},
			exportZoom: exportZoom
		});
```

`imageState.src` was incorrect

**Comment by scottcheng** [comment]
Seems like you solved it.
