### ISSUE TITLE
i cant seem to be able to upload a small image on a large container.... 

### ISSUE THREAD

**Issue by tomkidumbuyo** [scottcheng/cropit#163]
Can you help me... if i select a small image with small dimension it doesn't seem to upload to a large container. but it works fine with a small container... what am i supposed to do??...

**Comment by scottcheng** [comment]
By default cropit rejects images smaller than the container. If you want to allow small images, set `smallImage: 'allow'`. See <http://scottcheng.github.io/cropit/#docs-options-smallImage>

**Comment by tomkidumbuyo** [comment]
thanks but can i make the small images to fit on the container.... and make the new zoom the minimum zoom

**Comment by scottcheng** [comment]
Yes. Try `smallImage: 'stretch'`.

**Comment by tomkidumbuyo** [comment]
thanks
