### ISSUE TITLE
init and then imageSrc

### ISSUE THREAD

**Issue by rajankapila** [scottcheng/cropit#166]
This happens with the new dist file on init and then loading an imageSrc
TypeError: previewSize is undefined
jquery.cropit.js
Line 660
```

$('#image-editor').cropit({imageState : {'src' : src}});
```

**Comment by scottcheng** [comment]
Most likely you need to change `.cropit-image-preview` to `.cropit-preview`. I just put together a migration guide to 0.5 in [README](https://github.com/scottcheng/cropit#migrating-to-v05).
