### ISSUE TITLE
CSS: how to change image shape to circle?

### ISSUE THREAD

**Issue by ericgopak** [scottcheng/cropit#167]
Hi there and thank you for the great work! The plugin is amazing in many senses.

I have tried to apply CSS rules with **border-radius: 50%** and it worked on version **0.4.5**, but does not work anymore in **0.5.1**.

Could you please suggest any solution?

**Comment by ericgopak** [comment]
One possible solution on 0.4.5 is to add a nested <div> under the **cropit-image-preview** with white _background-color_ and a border-radius: 50%. This solution no longer works for the newer version.

**Comment by scottcheng** [comment]
You need to do two things:

1. Class names and markup structure were [changed](https://github.com/scottcheng/cropit/tree/dc55ddd71eb5461ae98b89fee769f0ad29610cf0#migrating-to-v05) in 0.5, and you need to set `border-radius` on `.cropit-preview-image-container`, not `.cropit-image-preview`.
2. The preview image used to be a `background-image`, and now it's an `img` tag. This seems to be an issue when you set `border-radius` and `overflow: hidden` on the container (`.cropit-preview-image-container`). Setting a `z-index` on the container seems to solve the problem. See [this post](http://stackoverflow.com/questions/5736503/how-to-make-css3-rounded-corners-hide-overflow-in-chrome-opera) for other solutions.

**Comment by ericgopak** [comment]
Perfect, thank you very much for the reply. It solved my problem
