### ISSUE TITLE
ImageState CORS for amazon s3 url for image src!

### ISSUE THREAD

**Issue by eliezerkombe** [scottcheng/cropit#172]
Allow Cross Origin worked well in the previous plugin however in the update, src: amazons3 url throws a cross origin error! Any ideas?

**Comment by eliezerkombe** [comment]
Actually never mind. I needed to enable CORS on the s3 bucket! did that and now it works like charms!

**Comment by Badman37** [comment]
can u give me example setting CORS on the s3 bucket ?. 
`<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>http://example.com</AllowedOrigin>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
</CORSRule>
</CORSConfiguration>`
but it's still not working.
