### ISSUE TITLE
How to drag in background zone ? 

### ISSUE THREAD

**Issue by ticlekiwi** [scottcheng/cropit#187]
Hi, great job with cropit !

I have a little request. I use this plugin to generate a crop with a tiny cropit preview ( width: 50px; height: 320px; ).
The cropit preview is so tiny it's very unpleasant to a user to drag and drop his picture.

Is it possible to add drag n drop functionnality also on background zone ? 

Thanks a lot !

**Comment by BugHunter2k** [comment]
Dup of #16?

**Comment by ticlekiwi** [comment]
Yeah it's same problem as #16 . I close this issue.
