### ISSUE TITLE
Doesn't work with PNG files

### ISSUE THREAD

**Issue by maiconcarraro** [scottcheng/cropit#198]
I selected some JPEG files and it worked, but none PNG files worked. I tried these files in demo page too and do nothing. What's the problem?

**Comment by maiconcarraro** [comment]
Solved with smallImage property :) awesome

**Comment by adw-cr** [comment]
@maiconcarraro  how you fix ?

**Comment by tamitutor** [comment]
Thank you @maiconcarraro!  I implemented Cropit in my React app and it wasn't working with PNG files for me either.  I was sure it was my code as it takes tweaking to get JQuery to work correctly inside of React.  I set the `smallImage` property to 'allow', and...VOILA!  It works!

This needs to be documented.
