### ISSUE TITLE
Adjust image to container

### ISSUE THREAD

**Issue by javiermarinros** [scottcheng/cropit#20]
It would be interesting if the plugin allow to edit an image with a different proportion of the container. 

For example, I want the user to upload an square picture, but him uploads a rectangular one. The current implementation doesn't allow to fit the image on the container, cropping the image. Without that limitation, the user would move and zoom the image until it fits the container, and then save it. What do you think?

**Comment by scottcheng** [comment]
@javiermarinros @phunksta I've added a `minZoom` option in 34f79e3850141741b4ad3950e6eeb5834571284e which works as follows:

> `minZoom` decides the minimal zoom level of the image. If set to `'fill'`, the image has to fill the preview area, i.e. both width and height must not go smaller than the preview area. If set to `'fit'`, the image can shrink further to fit the preview area, i.e. at least one of its edges must not go smaller than the preview area.

The default value is `'fill'`, consistent with previous default setting. Feel free to try it out (it's in the current master) and let me know how it works for you. Thanks!

**Comment by javiermarinros** [comment]
It works pretty well, the last thing needed would be to allow the user to drag the image around the container, in order to allow him center the image.

Thank you!

**Comment by scottcheng** [comment]
@javiermarinros Thanks for testing! Did you have to set `freeMove` to `true` to move the image around after zooming out? You should be able to achieve what you described above in the screenshot by only setting `minZoom` to `fit`. It doesn't allow you to drag the image off the preview area, but you should be able to drag it up and down, if the image is wider than the preview area.

**Comment by javiermarinros** [comment]
That's true! I didn't tried without freeMove, but it's better if the image cannot go off the preview area. Thank you!

**Comment by phunksta** [comment]
Hey @scottcheng,
Sorry for the delay, I'm back on the project using cropit today.
After some initial 'duh' moments (I'm quite noob with github) I found the new source in the master and tried it out.
Brilliant! what more do I need to say? It works very nicely indeed thank you!

What's more you can now brag that yours is pretty much the only crop plugin that allows you to do this gracefully!

The only possible improvement I could think of is having buttons on the cropit form that allow this mode to be toggled. Is that just a case of changing the options object, or would the form need re-initialising?

Thanks again!

**Comment by scottcheng** [comment]
@phunksta Thanks for trying it out!

Regarding toggling the mode, I don't think changing the options object is the best approach. Neither is re-initializing. Ideally there should be an API for it, e.g. `$el.cropit('minZoom', 'fit')`. Do you have a real world use case for this?

**Comment by phunksta** [comment]
No I think for our purposes what you've added is perfect. I just wasn't clear on how the options work, and you've answered that.
Thanks again! 

-------- Original message --------

**Comment by DevotionGeo** [comment]
@scottcheng when we set minZoom: to 'fit', the image while zoomed out moves freely. The user is not always very genius, so sometimes they move image to one side of the canvas (example#1), how can we force it centered while its smaller than the canvas (example#2)?

example#1 : http://i.imgur.com/UooWarh.jpg


example#2 : http://i.imgur.com/IiRD9HS.jpg

**Comment by mehdirad** [comment]
If user crop an image 1 time and then want to crop the the croped image again.it does not show the image.How I can fix it?

**Comment by nyn0x** [comment]
@DevotionGeo I fixed with css :
`.cropit-preview-image{
            float: left;
    }`

**Comment by CyrPen** [comment]
`.cropit-preview-image{ float: left; }`

Exactly what i was looking for ! Thanks

**Comment by kacpermaciejevvski** [comment]
Is there any way to 'cut' those 'transparent' sides of generated image, if the container is bigger than the image?

**Comment by shadaba1974** [comment]
how to add flip/flop button along rotation button? any idea, please let me know?
