### ISSUE TITLE
Saving images smaller than preview area

### ISSUE THREAD

**Issue by rvernon9** [scottcheng/cropit#203]
So if the preview area is 600 x 600 and the user chooses a file that is 400 x 200. It appears that cropit saves the image with a black background to make the image be 600 x 600. Is there anyway to save the file with its original size? I know I can check the offset which would probably tell me if the image is smaller than the preview area. I also tried using $imageCropper.cropit('disable');, but that didn't make any difference. I can't seem to get the original image to be sent to the server via POST. 

Any thoughts/suggestions?

**Comment by omartadj** [comment]
Save the image in png format and you will get a transparent background instead of black.
