### ISSUE TITLE
need help with background borders - not working for me

### ISSUE THREAD

**Issue by trstaley** [scottcheng/cropit#247]
Have added background borders to the demo file form.html using the following:
```
$('.image-editor').cropit({
  	imageBackground: true,
  	imageBackgroundBorderWidth: 15
});
```
However, borders do not display.  What am I missing?

**Comment by io-ma** [comment]
`$('#image-cropper').cropit({`
change your ID to image-cropper instead of using an image-editor class.

**Comment by trstaley** [comment]
Thank you so much.  My bad thinking the name could be changed.  Not smart on my part.
