### ISSUE TITLE
Code for better resize quality

### ISSUE THREAD

**Issue by fromvega** [scottcheng/cropit#36]
I adapted some code into your plugin so that the resulting image is of a better quality, with a lot less aliasing and without using too many resources. I was going to send you a pull request but then I realized the source code was written in coffee script. I wrote the new code in JavaScript and inserted it in the generated .js file. Are you interested in said code? What's the best way to share it?

**Comment by Biegal** [comment]
Maybe you could post some gist of that or something. That way we could figure the way to make a proper pull request more collectively ?

**Comment by scottcheng** [comment]
@fromvega Yes I'd be interested to see how you did that! Like @Biegal suggested, could you put your code/changes somewhere so we can see? You can even just create a pull request so we can see the comparison directly.

**Comment by bharatpatil** [comment]
This is must to have improvement.....!!!! I'm also looking for this. Explanation for similar problem can be found over here http://stackoverflow.com/questions/17861447/html5-canvas-drawimage-how-to-apply-antialiasing (if I've understood problem correctly.)

**Comment by Cain-Ish** [comment]
@scottcheng would be great if resize module would not cut quality. I use some of code that link @bharatpatil but it still not perfect.

**Comment by lorenz2304** [comment]
Found this code - maybe an option to squeeze that in? http://jsfiddle.net/gamealchemist/r6aVp/

**Comment by fromvega** [comment]
Guys, just take a look at the sample code I posted a while ago. I believe it solves this problem. Just copy and past the changes I made.

**Comment by scottcheng** [comment]
Thanks a lot for all the input; I finally adopted @fromvega's code.
