### ISSUE TITLE
CrossDomain support

### ISSUE THREAD

**Issue by vlatka-sinisa** [scottcheng/cropit#4]
If image loaded is from another domain then browser doesn't allow to get data. Is it possible for you to include some kind of workaround for this? (http://blog.codepen.io/2013/10/08/cross-domain-images-tainted-canvas/).

Besides that - great work!

**Comment by skitterm** [comment]
I kept getting the "tainted canvas" error until I went in and changed image.crossOrigin = "anonymous" to image.setAttribute('crossorigin', 'anonymous')  . Then everything worked.

**Comment by scottcheng** [comment]
@skitterm Interesting. Could you share what browser you tested in where `image.crossOrigin = "anonymous"` didn't work?

**Comment by skitterm** [comment]
I was in Chrome 42.

**Comment by mjaensch** [comment]
I have the same problem in Chrome 46 on windows.
The crossOrigin=Anonymous didn't work for me.
