### ISSUE TITLE
IE 11 Scroll Zoom not displaying as expected

### ISSUE THREAD

**Issue by lukejr** [scottcheng/cropit#41]
Issue with how the zoom scroll appears in IE11. Works fine in FF and Chrome.

![cropitzoom](https://cloud.githubusercontent.com/assets/1984576/6003355/048a99a0-aac9-11e4-85e8-21a8b8ab1331.PNG)

**Comment by scottcheng** [comment]
Hi @lukejr, thanks for reporting the issue! However I currently don't have access to IEs, and I have no intention to take the effort to fix the styling on IEs. Those who need to make cropit work on IEs can apply IE-specific CSS for slider, or use a non-native slider.
