### ISSUE TITLE
Calculate actual crop info

### ISSUE THREAD

**Issue by avatar** [scottcheng/cropit#45]
Hi,

I'd like to use cropit together with a thumbor server (https://github.com/thumbor/thumbor/wiki/Usage). 
For that i need to construct an url like this:

http://thumborserver.com/unsafe/[X1COORD]x[Y1COORD]:[X2COORD]x[Y2COORD]/[TARGET WITH]x[TARGET HEIGHT]/http://www.joomlaworks.net/images/demos/galleries/abstract/7.jpg

So for this i need to know the actual crop-coordinates on the fullsized image.

I'm having trouble figuring this out, can you help me?

Help is much appreciated!

Thanks,
Ben

**Comment by avatar** [comment]
I think i got the answer myself :)

```javascript
var offset = $('.image-editor').cropit('offset');
var imageSize = $('.image-editor').cropit('imageSize');
var previewSize = $('.image-editor').cropit('previewSize');
var zoom = $('.image-editor').cropit('zoom');
		  
var x1 = Math.round(Math.abs(offset.x) / zoom);
var x2 = Math.round((Math.abs(offset.x) + previewSize.width) / zoom);
		  
var y1 = Math.round(Math.abs(offset.y) / zoom);
var y2 = Math.round((Math.abs(offset.y) + previewSize.height) / zoom);
		  
console.log(x1+'x'+y1+':'+x2+'x'+y2);
```

seems to work for me...

**Comment by scottcheng** [comment]
Hey @avatar, your math looks good to me :) The only thing is that in normal cases `offset.x` and `offset.y` can only be negative, therefore instead of `Math.abs(offset.x)` you can just use `-x`.

Maybe I should add an API for this.

**Comment by williansebastiao** [comment]
Is there any way to retrieve the x and y coordinates? The width and height would also be possible? I'm trying to make a cut but I am not succeeding.

**Comment by avatar** [comment]
In my previous comment, you already got the x1, x2, y1 and y2 coordinates. If you want the width and height, you just have to subtract the x and y coordinates:

```
height = y2-y1;
width = x2-x1;
```

**Comment by williansebastiao** [comment]
My pictures have fixed width and height (250). my problem is in the coordinate.
I made the cut as the example x1 and y1.
see:
var x1 = Math.round (Math.abs (offset.x) / zoom);
var y 1 = Math.round (Math.abs (offset.y) / zoom);

. $ ('# x') val (x1);
. $ ('# y') val (y 1);
. $ ('# w') val (previewSize.width);
. $ ('# h') val (previewSize.height);

However coordinate is wrong.

**Comment by avatar** [comment]
Maybe put an example online? I don't really understand what you want to achieve.

**Comment by williansebastiao** [comment]
Hi Avatar!
I found the problem ...I can make the perfect cut when the image is proportional (200x200, 300x300 ... 1000x1000x). The problem occurs when the ratio is different ... (465x200). Thus I can not make the cut to the correct coordinate.

I plan on forcing the customer to use proportional images ...
