### ISSUE TITLE
How to minimize requested image using jquery cropit plugin?

### ISSUE THREAD

**Issue by AliAtes** [scottcheng/cropit#46]
http://stackoverflow.com/questions/28911351/how-to-minimize-requested-image-using-jquery-cropit-plugin

**Comment by scottcheng** [comment]
Added [a comment](http://stackoverflow.com/questions/28911351/how-to-minimize-requested-image-using-jquery-cropit-plugin#comment-46097794) in the thread.

**Comment by scottcheng** [comment]
Seems like it's resolved on the stackoverflow thread :)
