### ISSUE TITLE
Access to the final cropped image

### ISSUE THREAD

**Issue by Dajust** [scottcheng/cropit#47]
How do I access the cropped image -  the final result after cropping? I need a way to get it so I can send this to the server to be saved. Think profile pictures.

**Comment by piotrze** [comment]
@Dajust According to documentation http://scottcheng.github.io/cropit/ you can use:

```javascript
// Returns the cropped image in Data URI format.
// The second argument `options` takes the following keys:
// - [type='image/png'] exported image type.
// - [quality=.75] exported image quality, only works when type is
//     'image/jpeg' or 'image/webp'.
// - [originalSize=false] when set to true, export cropped part in
//     original size, overriding exportZoom.
// - [fillBg='#fff'] if `type` is 'image/jpeg', this color will be
//     filled as the background of the exported image.
$imageCropper.cropit('export', {
  type: 'image/jpeg',
  quality: .9,
  originalSize: true
});
```
The $imageCropper is an instance of cropit object.
```javascript
$imageCropper = $('#image-cropper').cropit();
```

**Comment by Dajust** [comment]
@piotrze Thanks so much. But the  'export' method only returns the dataURL. 

See the return statement of this code that it calls...
```
Cropit.prototype.getCroppedImageData = function(exportOptions) {
            var canvas, canvasContext, croppedSize, exportDefaults, exportZoom;
            if (!this.imageSrc) {
                return null;
            }
            exportDefaults = {
                type: "image/png",
                quality: .75,
                originalSize: false,
                fillBg: "#fff"
            };
            exportOptions = $.extend({}, exportDefaults, exportOptions);
            croppedSize = {
                w: this.previewSize.w,
                h: this.previewSize.h
            };
            exportZoom = exportOptions.originalSize ? 1 / this.zoom : this.options.exportZoom;
            canvas = $("<canvas />").attr({
                width: croppedSize.w * exportZoom,
                height: croppedSize.h * exportZoom
            }).get(0);
            canvasContext = canvas.getContext("2d");
            if (exportOptions.type === "image/jpeg") {
                canvasContext.fillStyle = exportOptions.fillBg;
                canvasContext.fillRect(0, 0, canvas.width, canvas.height);
            }
            canvasContext.drawImage(this.image, this.offset.x * exportZoom, this.offset.y * exportZoom, this.zoom * exportZoom * this.imageSize.w, this.zoom * exportZoom * this.imageSize.h);
            return canvas.toDataURL(exportOptions.type, exportOptions.quality);
        };
```
But what I need is the raw BLOB of the cropped image. I'm currently playing with the `HTMLCanvasElement.toBlob()` method, perhaps I can fix it. I know this is not fully implemented in browsers yet. So I'll appreciate any better way.

**Comment by scottcheng** [comment]
@Dajust it seems like you can directly convert DataURI to Blob: <https://gist.github.com/exinferis/4216618>. There is even a library for that: <https://github.com/component/data-uri-to-blob>.

Out of curiosity, why would you want a Blob instead of DataURI?

**Comment by Dajust** [comment]
@scottcheng I didn't fully understand the DataURI thing. 

My thought was that the DataURI - as the name suggests - was just a URI - like a pointer or a link to the real cropped image. Thus I was looking for the cropped image.

I later understood that the DataURI has the real image in it. Its base 64 encoded. So I can send and save the DataURI to the server. Then, the server end can either decide to decode it before saving or save it as DataURI. Either way, it would still be saved and sent back to the browser as an image.

I've already seen your answer and it accomplished my initial intent. Also you can directly convert the canvas to Blob with: ```HTMLCanvasElement.toBlob()``` But this is not yet fully implemented in browsers.

However, I've decided to simply save the DataURI to the server.

**Comment by scottcheng** [comment]
@Dajust You are right :)
