### ISSUE TITLE
Turn off upscaling of images?

### ISSUE THREAD

**Issue by deronsizemore** [scottcheng/cropit#48]
I need images to be a certain size (or larger). Right now, I've noticed that smaller images are upscaled to fit the preview area. Is there a way to turn this off and require a minimum size?

Thanks

**Comment by scottcheng** [comment]
Good point. I just added `rejectSmallImage` option in 4110ecb98e9064c8dc1999b09938e013f4dce49f and 79af50c36c6819c3bfe0fd10f9418f671e01113c. When it's `true`, if the image is smaller than preview size, it will call `onImageError` callback with an error `{ code: 1, message: 'Image is too small.' }`. Then you can show an error message, disable the widget, etc.

**Comment by deronsizemore** [comment]
Awesome! Thanks for the quick fix.

**Comment by aiolos** [comment]
Nice feature, exactly what I needed, but I think this feature should also take the zoom level into account. For example: 

`if (this.options.rejectSmallImage && (this.imageSize.w < this.previewSize.w || this.imageSize.h < this.previewSize.h)) {`

should be 

`if (this.options.rejectSmallImage && (this.imageSize.w < (this.previewSize.w * this.options.exportZoom) || this.imageSize.h < (this.previewSize.h * this.options.exportZoom))) {`

I also see the image is still loaded, shouldn't that also be prevented?

**Comment by scottcheng** [comment]
@aiolos Yep you are right about `exportZoom`. Thanks for pointing it out! Fixed in 8f2917ce3be0bb3551b28a9486007cb37f5e78d4.

Regarding whether the image should be loaded when it doesn't meet the size requirements, the reason it loads is because it's a smaller change implementation-wise. I do agree that keeping the old state might make more sense, and I may change it in the future.

**Comment by deronsizemore** [comment]
So I'm finally getting around to messing around with this and it seems the rejectSmallImage is working but I've yet to be successful in adding in the onImageError callback. Can you maybe give me a basic example of how I'd do that? I couldn't find an example in the docs.

Thanks

**Comment by deronsizemore** [comment]
Well, I thought rejectSmallImage was working. Turns out I just had missed a comma and nothing was loading (not even images that are large enough). Images on my end are still upscaling even with the rejectSmallImages in place:

    $(function() {
				$('.image-editor').cropit({
					imageState: {
						src: ''
					},
					rejectSmallImage: true,
				});
			});

What am I doing wrong here?

**Comment by deronsizemore** [comment]
So I noticed that I hadn't downloaded the correct version, I downloaded the master version instead of the commit with the changes you made.

That said, I'm still struggling to get it working. Here's my updated code which seems to have zero effect on anything:

    $(function() {
				$('.image-editor').cropit({
					imageState: {
						src: ''
					},
					previewSize: {
						width: 400,
						height: 300,
					},
					rejectSmallImage: true,
				});
			});

If I try to upload an image smaller than the preview size, it still puts that image inside the preview area and upscales it which I didn't think it should be doing with "rejectSmallImage" in place?

**Comment by scottcheng** [comment]
@deronsizemore Sorry for the delay. You are right that the image would still loads even if you pass in `rejectSmallImage: true` and select a small image, and I may change that soon. However it also fires a `onImageError` callback, where you could tell the user to use a larger image. Try something like this:

```javascript
$('.image-editor').cropit({
  rejectSmallImage: true,
  onImageError: function() {
    console.log('error');
  }
});
```

**Comment by deronsizemore** [comment]
Thank you for the response! 

Thanks for the code as well. I just wasn't sure how to write that onImageError function, but that makes sense now.

Considering how the image still loads even when it's too small, I would ideally like to display a message letting them now (which I know how to do) as well as removing the image from the preview area. Would that be easy to do? Just put the code inside of the onImageError function to remove the image from the preview area?

**Comment by scottcheng** [comment]
I have plans to make rejecting smaller image (and not loading it at all) a default, but that'll be in the next major version which I'm not sure exactly when I'll have time to finish. In the meantime I'm afraid there's no non-hacky way to remove an image (related to #26). Right now the closest thing you can do is:

```javascript
$('.cropit-image-preview').css('background-image', ''); // Your selector may vary
$('.cropit-image-background').removeAttr('src'); // If you are using image background
```

**Comment by deronsizemore** [comment]
Ok, thanks. I'm okay with hacky as long as it work. :) Thanks again. I'll try to keep an eye out on the next release.

**Comment by scottcheng** [comment]
Hey @deronsizemore @aiolos, just wanted to follow up that in v0.3 cropit rejects small image by default and does not load it into preview and v0.4 adds more flexible support for small images via `smallImage` option.

**Comment by deronsizemore** [comment]
@scottcheng Thanks for the update. Sorry for my delayed reply. Not sure how I missed this update; I'm just getting around to being able to start working on this again. I'll let you know how it goes. Thanks.
