### ISSUE TITLE
Upload original size

### ISSUE THREAD

**Issue by andrefigueira** [scottcheng/cropit#50]
Hi I'm using this for a banner upload but the size is too small, how can I send my server the original size, I could not see how I can do this, the code I have it:

    $('#image-cropper-banner').cropit({
        imageBackground: true,
        imageBackgroundBorderWidth: 50,
        export: {
            quality: .9,
            originalSize: true
        },
        imageState: {
            src: 'img/select-image.jpg'
        },
        onFileChange: function(){
            $('.apply-banner-action').removeAttr('disabled');
        }
    });

**Comment by andrefigueira** [comment]
Figured it out! Sorry :) Have to use exportZoom! :+1:

**Comment by sidaurukfreddy** [comment]
Hello @andrefigueira  please post the code
