### ISSUE TITLE
Hide zoom if image is upscaled..?

### ISSUE THREAD

**Issue by andykisaragi** [scottcheng/cropit#52]
Hi

Just wanted to check whether this already exists before I jump into code :)

It would be nice to be able to optionally hide the zoom control if the uploaded image is too small to be zoomed - I'm working on a site with large user contributed images which often end up being upscaled, and the presence of the unusable zoom control is quite confusing for users...

Cheers

**Comment by andykisaragi** [comment]
My quick fix for this, I added a couple of lines direct to jquery.cropit.js:
`this.$zoomSlider.show();` and `this.$zoomSlider.hide();` to Cropit.prototype.enableZoomSlider and Cropit.prototype.disableZoomSlider respectively.
I'm not familiar with coffeescript atm but at some point when I have time I'll try to add this properly as a setting

**Comment by scottcheng** [comment]
I suppose a better way may be passing in [`onZoomEnabled`](https://github.com/scottcheng/cropit/blob/1fb6fa9e11e103faad29891c2c67e74d376fddda/src/cropit.coffee#L283) and [`onZoomDisabled `](https://github.com/scottcheng/cropit/blob/1fb6fa9e11e103faad29891c2c67e74d376fddda/src/cropit.coffee#L287) options, where you can show/hide the slider. IMO I don't think hiding the slider is generic enough to be added as an option.
