### ISSUE TITLE
Crop Image in Circular mode

### ISSUE THREAD

**Issue by dhiman252** [scottcheng/cropit#53]
Is there any way such that we can crop image of circular shape ?

Right now we specify the width and height of the div containing this CSS class("cropit-image-preview").

If i provide a property of border-radius:50% then the shape of the div changes to circular but the image I get after croping is rectangular in shape.

**Comment by Dazag** [comment]
I use cropit to do images in a circle shape. As you said you can make the container look like a circle, but it will be a square. My question is why do you want the image to be a circle when you can use border radius to give circle shape to any image with CSS?

**Comment by scottcheng** [comment]
@dhiman252 No AFAIK there is no easy way to do that, but what @Dazag suggests should work.
