### ISSUE TITLE
Center preview image

### ISSUE THREAD

**Issue by skitterm** [scottcheng/cropit#54]
I'm using the imageBackground functionality to show a larger area of the photo than the region I will crop. I would love it if the image would center itself within the croppable region when it loads in (if a tall image, it would center vertically; if a wide image, it would center horizontally). I assume I could hack it on my own using setOffset, but I figured this would be a nice addition to the library.

Let me know if it already exists and I've missed it somehow.

**Comment by scottcheng** [comment]
Great suggestion. I'll add it in the next version.

**Comment by sidaurukfreddy** [comment]
where is the doc about images in the center
