### ISSUE TITLE
Save file to local server

### ISSUE THREAD

**Issue by Ahmadrameen** [scottcheng/cropit#56]
How to save the file to local server. Instead of viewing in new window.

**Comment by monoescape** [comment]
I'd also like to know, if this is possible at all.

**Comment by Dazag** [comment]
Well guys, I remember you have to make something like,
 var foo = $(' #cropit-element').export(); 
then you will have the picture in "foo" so you manage it as you wish from there. 
Send it through AJAX to you server or wherever you want.

**Comment by scottcheng** [comment]
@Dazag is correct. E.g. see the [form example](https://github.com/scottcheng/cropit/blob/1fb6fa9e11e103faad29891c2c67e74d376fddda/demo/form.html).
