### ISSUE TITLE
Webkit browser prevents onImageLoaded from firing when selecting the same file again

### ISSUE THREAD

**Issue by sudent** [scottcheng/cropit#57]
Hello, awesome library and thanks for this!

Anyway, I don't know if I'm doing this the wrong way, but I have a use-case of executing certain tasks after a user have selected a file using the onImageLoaded method (I need the image for executing the tasks but before it being exported, hence after the image is fully ready).

The first time, it's all runs well. The user will have a choice to proceed (I then export the selected image) or cancel everything.

The issue is that, when user decides to cancel, and then repeat the process with the same file previously, the callback of onImageLoaded is not called and I can't execute my task. This is when using webkit browsers (chrome/safari) but not in firefox.

I work around this by adding onImageLoaded as a method to the cropit object and calls it manually when detecting the user is on webkit browser. Doing this in onFileChange or onImageLoading, I will still need to detect if the image is already loaded, which is the responsibility of onImageLoaded anyway. I figured webkit already 'loads' the image if choosing the same file consecutively hence the onload event is not called.

Am I doing this right or am I missing something obvious or completely doing it the wrong way? Thanks!

**Comment by scottcheng** [comment]
Sorry about the delay. I'm not very sure what you mean by "cancel", but I suppose what is happening is, when the user "cancels" and comes back, the preview area is re-rendered, removing the previously selected image, but the file input is not reset and still holds the old image in it. If this is the case, I'd suggest that the preview area and the file input should always stay in sync. Specifically in this case, when the user cancels and comes back, either the preview area should keep the previously selected image, or the file input should be emptied/re-rendered.
