### ISSUE TITLE
Zoom Slider not working

### ISSUE THREAD

**Issue by usmanshakil** [scottcheng/cropit#58]
When an image is selected from local directory the zoom slider gets disabled.

**Comment by scottcheng** [comment]
Is your image larger than the preview area?

**Comment by usmanshakil** [comment]
i've uploaded big as well as small image

**Comment by scottcheng** [comment]
That's weird. Have you tried the demo [here](http://scottcheng.github.io/cropit/)? If it happens on the demo, can you post the image that you are using?

**Comment by usmanshakil** [comment]
i've uploaded the image on demo but same result. Is there any issue
regarding local uploads?

**Comment by usmanshakil** [comment]
If this is the image size issue then what size should i put on? Bigger than
the container?

**Comment by scottcheng** [comment]
The designed behavior is that, when the selected local image is smaller than the container on either side, the zoom slider would be disabled.

**Comment by usmanshakil** [comment]
oh got it, i must say you made a good thing.

**Comment by scottcheng** [comment]
Thanks, glad you liked it.
