### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by sahanDissanayake** [scottcheng/cropit#59]
Nice plugin.. Just what i was looking for

Any thoughts @scottcheng

**Comment by scottcheng** [comment]
Thanks @sahanDissanayake. It uses FileReader under the hood so IE10+ ([details](http://caniuse.com/#feat=filereader)).

**Comment by sahanDissanayake** [comment]
:+1:

**Comment by sahanDissanayake** [comment]
you will not worry about making it backward compatible right ? #justcurious

**Comment by scottcheng** [comment]
No I'm not too keen on supporting ancient browsers. :angel:

**Comment by scottcheng** [comment]
BTW, the slider may look different on IEs, but you can always replace the native slider with a custom one.
