### ISSUE TITLE
Image type png and jpg

### ISSUE THREAD

**Issue by KamalAhmad** [scottcheng/cropit#60]
Hi i have some problem use two imageformat to upload: jpg and png ... 
Im trying jpg and png

The orginal code is:
var imageData = $('image-editor').cropit('export', {type: 'image/jpeg' quality: .9,} );

i would like to use both format in same code: how do i do that???

example ? can the script know what image to upload? jpeg or png?
The upload does not work for two format??

IF JPG do this:
var imageData = $('image-editor').cropit('export', {type: 'image/jpeg'´ quality: .75,} );
IF PNG do this:
var imageData = $('image-editor').cropit('export', {type: 'image/png'´ quality: .9,} );

something like this i want..

/ Best regards

Kamal Ahmad

**Comment by scottcheng** [comment]
The cropper takes any image format, even animated gifs. The format argument you pass in `export` method only determines the *output* format.

What the cropper does in in middle is it takes a snapshot of part of the image, hence the output format has nothing to do with the original image format.

**Comment by scottcheng** [comment]
The cropper takes any image format, even animated gifs. The format argument you pass in `export` method only determines the *output* format.

What the cropper does in in middle is it takes a snapshot of part of the image, hence the output format has nothing to do with the original image format.
