### ISSUE TITLE
Changing dimensions preview container after instantiation 

### ISSUE THREAD

**Issue by perrykipkerrie** [scottcheng/cropit#61]
First I want to say what a wonderfull plugin cropit is, my compliments.

When the preview container size is changed after instantiation, the export function uses the old dimensions to create the export image. Does somebody know if there is a solution available for this?

Kind regards

**Comment by scottcheng** [comment]
Please make sure to use `previewSize` method when changing preview container dimensions, and the export should work fine.

```javascript
$imageCropper.cropit('previewSize', { width: 800, height: 450 });
```
