### ISSUE TITLE
How to rotate image!!!

### ISSUE THREAD

**Issue by nguyentungson** [scottcheng/cropit#62]
Hi all!
I want when selecting the image you can rotate the image. The thing that I have done but when cutting the image then it is not true to picture when rotated. So how? Many thanks!

**Comment by scottcheng** [comment]
I'm afraid rotation is not supported yet. I assume the reason your approach does not work is because you are rotating the entire canvas, therefore the image stays upright with regard to the canvas.

**Comment by lorenz2304** [comment]
Have the problem with cropit not reading EXIF orientation information of photos taken e.g. with the iPhone.  Any plans / possibilities to squeeze this into the library?

**Comment by lorenz2304** [comment]
I see you seem to preserve some of the EXIF headers while cropping. Unfortunately, the orientation header is not one of these. Please could you take care of this? Best would be to immediately show the loaded image in correct orientation, second best would be to at least preserve the orientation EXIF header..
