### ISSUE TITLE
Zoom out even further

### ISSUE THREAD

**Issue by dmikester1** [scottcheng/cropit#64]
I have my image preview set to 300 x 174 because that is the dimensions of the image I want exported.  Now for some pictures, 174px is too short and cuts off part of the desired part of the image.  Is it possible to zoom out further and just add white padding to the left and right?

**Comment by scottcheng** [comment]
In the latest version in master branch there is a `minZoom` option, which if you set to `'fit'` cropit will allow the image to be zoomed out until it fits the container. This is a breaking change so it won't be available until the next major release.

**Comment by giolvani** [comment]
+1

**Comment by rakeshaspl** [comment]
Can we get more zoom out then fit ?
