### ISSUE TITLE
File preview not working on safari ( FileReader issue )

### ISSUE THREAD

**Issue by yogeshsaroya** [scottcheng/cropit#65]

**Comment by scottcheng** [comment]
@yogeshsaroya Could you further explain the problem please -- what exactly is not working on Safari?

**Comment by yogeshsaroya** [comment]
@scottcheng  on safari, open this http://scottcheng.github.io/cropit/ , now try to upload new image using " Select new image  " button then check error message on console ( ReferenceError: Can't find variable: FileReader )

Thanks

**Comment by scottcheng** [comment]
What version of Safari are you using? FileReader is supposed to work on Safari 6+ (see [CanIUse](http://caniuse.com/#feat=filereader)).

**Comment by yogeshsaroya** [comment]
hmmm.. i am using ver 5.1.7.

**Comment by scottcheng** [comment]
Well that's why...
