### ISSUE TITLE
How to crop 500x500px image on 320 screen (mobile) without scrolling ?

### ISSUE THREAD

**Issue by yogeshsaroya** [scottcheng/cropit#66]

**Comment by scottcheng** [comment]
Try the `exportZoom` option.

> The ratio between the desired image size to export and the preview size. For example, if the preview size is `300px * 200px`, and `exportZoom = 2`, then the exported image size will be `600px * 400px`. This also affects the maximum zoom level, since the exported image cannot be zoomed to larger than its original size.
