### ISSUE TITLE
Does Cropit support IE 9

### ISSUE THREAD

**Issue by misternon** [scottcheng/cropit#67]
I have found many way to solve this problem but I have no idea about it. Is it possible that Cropit can run on IE9 Thank you

**Comment by timruby** [comment]
I was wondering this myself. I'm pretty sure that IE9 doesn't support the fileReader API, but any suggestions on a solution for IE9 would be really helpful.

**Comment by troylarson** [comment]
I was wondering this as well... for IE8. I know IE8 doesn't support the canvas tag (and a myriad of other features) but I was wondering if it was possible to support cropit with the use of other plugins like excanvas. I really like this plugin, so if there's no possible way to support it in IE8 I'll be bummed.

**Comment by scottcheng** [comment]
IE8 and 9 do not support [FileReader](http://caniuse.com/#search=filereader), and Cropit does not natively support them. I have yet to try to work with IE8/9, but some of [these polyfills](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-browser-Polyfills) may help: [FileReader](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-browser-Polyfills#user-content-file-api), [Canvas](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-browser-Polyfills#canvas).

BTW, [just for fun](http://9gag.com/gag/aozNZ1X/Conversation-Between-Browsers) :smiley:

![](http://img-9gag-fun.9cache.com/photo/aozNZ1X_700b_v2.jpg)

**Comment by misternon** [comment]
Oh Thank you. I forgot about this cropit using FileReader but Thank you for your answer

**Comment by benclarke** [comment]
does anyone have an opinion on the best IE 8+ compatible js cropper? I have a large international audience for my site...

**Comment by troylarson** [comment]
Hey Ben, I wound up using Jcrop v0.9.12 on my site for IE8 users. I think that's a pretty popular plugin, but the downside is you have to write the method to actually crop the photo on the server. I got it working, though. Good luck!
