### ISSUE TITLE
Using cropit with webpack results in a warning

### ISSUE THREAD

**Issue by SpaceK33z** [scottcheng/cropit#69]
Hi, after upgrading to `0.3.0` I'm getting this error when using it with webpack:

```
WARNING in ../~/jquery/dist/jquery.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ../~/jQuery/dist/jquery.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```

After looking in `dist/jquery.cropit.js`, it appears this is because of `module.exports = factory(require("jQuery"));`. It probably uses the capital because in `webpack.config.js` it says:

```
externals: { 'jquery': 'jQuery' },
```

Problem is that if you remove this line, cropit does not work anymore when you're not using a module loader (because it would then search for `jquery` instead of `jQuery`).

**Comment by scottcheng** [comment]
4959c58 should fix this. Would you please try and see if it works now?

**Comment by SpaceK33z** [comment]
Awesome, that works :). Thank you!
