### ISSUE TITLE
Min zoom less than zero

### ISSUE THREAD

**Issue by giolvani** [scottcheng/cropit#72]
There's any way to set minzoom as "-1", so the image could decrease until zero size. It would be very usefull for image without padding or margin.

Hope I've been clear

**Comment by scottcheng** [comment]
Could you further explain where zooming image to zero size might be useful?

**Comment by giolvani** [comment]
Ok, really, images with zero size wouldn't very useful, but can to decrease images at least 50% from original size would be a good idea.

**Comment by scottcheng** [comment]
I see -- you mean zoom down to smaller than the container. In that case do you want the minimum zoom to be a constant ratio to the original size of the image, or a constant size/ratio to container size?

**Comment by giolvani** [comment]
Thinking better, I guess this feature makes no much sense.

Sorry for take your time.
