### ISSUE TITLE
Please, fix error in docs about $zoomSlider

### ISSUE THREAD

**Issue by StraDIVar** [scottcheng/cropit#73]
In docs on http://scottcheng.github.io/cropit/ there is an error:
should be `$zoomSlider` instead of `$imageZoomInput` option

**Comment by scottcheng** [comment]
Fixed in 8fccb9d93a5f58179e07254610682d093fbde42d. Sorry the website was outdated for quite some time.

**Comment by StraDIVar** [comment]
Thanks! You make a nice plugin!
