### ISSUE TITLE
small images doesn't work (?)

### ISSUE THREAD

**Issue by oscargglez** [scottcheng/cropit#80]
Hi, I updated to the new code but when I put an small image (more small than a container preview) this image doesn't load. I try to set the new property smallImage to allow but nothing. By the way, with the old code all runs fine.

Thanks :-)

**Comment by scottcheng** [comment]
It should work. Do you mind posting your code snippet?

**Comment by oscargglez** [comment]
Yep!, here you are: https://jsfiddle.net/oscargglez/tjLL7m4u/
Example image: http://www.bewithyou.es/test/sherlock-holmes.jpg

I'm not an expert ... v_v

**Comment by scottcheng** [comment]
Looking at your jsfiddle, it seems like you need to initialize cropit first (by calling `$editor.cropit(options)`) before you can call export.

**Comment by giolvani** [comment]
If you are using the v0.4.0, the property smallImage: 'allow' should be work.
