### ISSUE TITLE
Image file upload fails when allowCrossOrigin is true in 0.4.0

### ISSUE THREAD

**Issue by willingchangthernguyen** [scottcheng/cropit#81]
the issue still happens although we set crossOrigin = true

**Comment by scottcheng** [comment]
What browser and version are you using?

**Comment by willingchangthernguyen** [comment]
Chromium
Version 41.0.2272.76 Ubuntu 14.04 (64-bit)
Firefox for ubuntu
38.0

**Comment by scottcheng** [comment]
Please try 0.4.1 and see if it's fixed.

**Comment by willingchangthernguyen** [comment]
Hi
it isn't ok
it should be 
            if (this.options.allowCrossOrigin) {
                this.image.crossOrigin = "Anonymous";
            }
Thanks
