### ISSUE TITLE
.cropit('export') returns different data on different browsers

### ISSUE THREAD

**Issue by staylor5** [scottcheng/cropit#82]
https://jsfiddle.net/staylor5/yj87bg0L/2/
The plugin shown in the jsfiddle does not work on a mobile browser (Chrome version 43.0.2357.93). This was tested on other mobile devices and desktop browsers, and works fine.

**Comment by scottcheng** [comment]
Does the [cropit doc page](scottcheng.github.io/cropit/) work for you on mobile Chrome? It's working well for me on iOS Chrome 43.

Regarding export data varying from browser to browser, I think that's because browsers implement canvas APIs differently.

**Comment by staylor5** [comment]
Let me check since I have iOS. I know the chrome version it is not
supporting is on an android device.

**Comment by staylor5** [comment]
Images can be loaded in but the export piece is not testable. Also, we want the returned value to be the same so that it the same value across all browsers.

**Comment by scottcheng** [comment]
Exporting on iOS Chrome is working for me. Sorry I don't have an Android device at hand and can't test on it.

For the return value, I'm afraid that's not something the plugin can control.
