### ISSUE TITLE
How to remove the image loaded or selected?

### ISSUE THREAD

**Issue by duanmao** [scottcheng/cropit#83]
It seems that I cannot find a way to remove the image loaded or selected... could someone kindly introduce me?
Thanks in advance.

**Comment by scottcheng** [comment]
There is none at the moment. It could be a useful addition.

**Comment by mucahit** [comment]
Hi, This very easy, look.

```javascript
cropitElement.find('input[type="file"]').change(function(){
	//Do something
});
```

**Comment by scottcheng** [comment]
Duplicate with #26.

**Comment by ivko999** [comment]
This seemed to work for me:

$(".cropit-preview").find("img").attr("src", null)

**Comment by noveweb** [comment]
Ultimate solution:

Inside of callback "HIDDEN MODAL" insert this:

$('.cropit-preview').removeClass('cropit-image-loaded');
				$('.cropit-preview-background').attr('src','');
				$('.cropit-preview-background').removeAttr('style');
				$('.cropit-preview-background').attr('style','position: relative; left: 30px; top: 30px; transform-origin: left top 0px; will-change: transform;');
				$('.cropit-preview-image').attr('src','');
				$('.cropit-preview-image').removeAttr('style');
				$('.cropit-preview-image').attr('style','transform-origin: left top 0px; will-change: transform;');
				$('input.cropit-image-input').val('');
				$('.cropit-image-zoom-input').val('0');


Done! Now after modal close the cropit will reset!
