### ISSUE TITLE
Height image issue

### ISSUE THREAD

**Issue by willingchangthernguyen** [scottcheng/cropit#84]
When I upload an image with height > width many times , cropit can not load the image 
version 0.2.0 runs ok
Thanks

**Comment by scottcheng** [comment]
Can you reproduce it on the [demo page](http://scottcheng.github.io/cropit/)? If so, could you share the image you tested with?

**Comment by willingchangthernguyen** [comment]
![van-mai-huong-2-7394-1435630545](https://cloud.githubusercontent.com/assets/815940/8713716/50a05e26-2b96-11e5-8596-0de4816a437b.jpg)

**Comment by scottcheng** [comment]
It works for me with this particular image. What browser and version are you using?

**Comment by willingchangthernguyen** [comment]
Hi
Chromium Version 44.0.2403.89 Ubuntu 14.04 (64-bit)
Firefox for Ubuntu 40.0
I don't think it is because of version browsers 
maybe because the preview size : width : 533px, height : 300px
Thanks

**Comment by scottcheng** [comment]
Yes I believe that's the reason -- image width (500) is smaller than preview width (533). You can either allow small image by passing in `smallImage: 'allow'` to allow selecting small images, or using `onImageError` callback to report errors.
