### ISSUE TITLE
add 'destroy' option to the Docs

### ISSUE THREAD

**Issue by saintach** [scottcheng/cropit#87]
I needed to changed the crop dimension for my project but it took me a while to look for how to reinitialize 'cropit'. After looking thourgh the code, I used $cropitImage.cropit('destroy'). I think it would be nice to put that on the docs.

**Comment by scottcheng** [comment]
To change crop dimension you can use `$imageCropper.cropit('previewSize')`. Calling `.cropit('destroy')` and reinitiating the plugin may have side effects, since each time the plugin is initiated it adds DOM elements within `$imageCropper`, and `$imageCropper.cropit('destroy')` does not remove them. Normally  reinitialization should not be necessary.

**Comment by DeathAngelDaemon** [comment]
I've the same problem.
The user can choose (with the help of three radio buttons) which image should be loaded. Upon the selection I get the dimension of the crop and it should change dynamically.

I've tried the following:
```javascript
$imageCropper.cropit({
  allowDragNDrop: true,
  height: variable-with-height,
  width: variable-with-width,
  ...
});
```

That works for the first select of one of the options. But if I choose another option, nothing changed. The crop keeps the first given dimensions.

I've also tried the option `previewSize`, but now not even the first select works.
I've tried the following:
```javascript
$imageCropper.cropit({
  allowDragNDrop: true,
  previewSize: {
    height: variable-with-height,
    width: variable-with-width
  },
  ...
});
```
and it ends up with just (no dimensions!):
```
<div class="cropit-image-preview" style="background-repeat: no-repeat;"></div>
```

Maybe you can give me a hint, what I can do, if I should not use `.cropit('destroy')`.

Addition: the cropit function is called everytime when the selection of the radio buttons changes.

**Comment by scottcheng** [comment]
@DeathAngelDaemon If I understood correctly what you need is the following:

1. Initiate cropit first (and only once) with default width and height.
2. When a radio button is clicked, update the preview dimensions by calling `$imageCropper.cropit('previewSize', { width: newWidth, height: newHeight })`.

**Comment by DeathAngelDaemon** [comment]
@scottcheng You're right!
I've now re-factured my code and created a new function to update the cropit on radio button change (just the previewSize, as you posted it). Now it works as expected.

Thanks for the input to make the penny dropping at last. ;)

**Comment by scottcheng** [comment]
Great to hear that :)
