### ISSUE TITLE
Uploaded image isn't showing in preview div container

### ISSUE THREAD

**Issue by richyarD** [scottcheng/cropit#88]
So I got this div container as a place for image preview and when I upload image, I see this: `<div class="row col-xs-12 cropit-image-preview" id="cropit-image-preview" style="background-repeat: no-repeat;"></div>`
There's no image set as background. The image in preview is visible only after 2nd or 3rd time I cancel image from file input and upload it one more time.
Tested on Chrome 43.0.2357.134 (64-bit) and Firefox 39.0 on Ubuntu 14.04 LTS.
Need any details?

**Comment by richyarD** [comment]
When I upload picture I get this in dev console:
> GET [object%20ProgressEvent]:1
http://127.0.0.1:8000/[object%20ProgressEvent] 404 (File not found)```

And when click on this [object%20ProgressEvent] I'm transferred to Resources tab, to Images and see this:
> [object%20ProgressEvent]
Dimensions 0 × 0
File size 146 B
MIME type text/html
URL http://127.0.0.1:8000/[object%20ProgressEvent]

**Comment by scottcheng** [comment]
Did you just pick a local file? Any chance you know why it's trying to load `http://127.0.0.1:8000/[object%20ProgressEvent]`?

**Comment by richyarD** [comment]
Yes I picked a local file. No chances to know why its behaved like this.

**Comment by scottcheng** [comment]
Does the [demo site](http://scottcheng.github.io/cropit/) work on your browsers?

**Comment by richyarD** [comment]
Yeah it works. So I must had some smelly code which did this thing..

**Comment by scottcheng** [comment]
Do you mind sharing your code snippet then?

**Comment by richyarD** [comment]
Not any more. I've deleted it and starting something else.

**Comment by scottcheng** [comment]
Well then I'm afraid there's nothing I can do to help.
