### ISSUE TITLE
Image quality issues

### ISSUE THREAD

**Issue by mapbuh** [scottcheng/cropit#91]
I have issues with both 0.4.1 and 0.4.0 where big enough image when cropped is not looking good in export ( needs antialiasing or such ). Image is 2000x1500 ... cropped to 400x300.

I have tried different options, also tried the same image on the examples on http://scottcheng.github.io/cropit/. And the curious thing is everytime the exported image looks worse then the preview. The preview is smooth and antialiased while the exported image is pixelated. 

Can provide the image on request via mail, because of privacy matters.

**Comment by scottcheng** [comment]
I have tested with 4000x6000 images and got pretty good results. Could you share you image with me through email at <me@scottcheng.com>?

**Comment by mapbuh** [comment]
Done. I've sent the example photo via e-mail

**Comment by hamzazafeer** [comment]
@scottcheng my image is `1920 * 2379`. my preview area widht is `250 * 250`.  after exporting image become `250 * 250`.  Image got pixelated. I want image image should be `1920 * 2379`.

How to solve this issue ?

**Comment by mapbuh** [comment]
I vaguely remember in the end I used the frontend of cropit, then sending the original image + zoom and offset and doing the resizing with different lib. Scott wrote me then that "there is not much I can do at the moment".
