### ISSUE TITLE
Rotating image / Fixing issue with uploading portrait image

### ISSUE THREAD

**Issue by peterbournecommunications** [scottcheng/cropit#92]
Hi, Great plug in... thanks!

However, I'm having problems when I use a portrait image straight from a camera (Canon 5D in this case). The image comes in 90degrees rotated.

I could really do with this being detected and corrected at the image display stage.
Failing that - it would be great to be able to manipulate the uploaded image by using the onImageLoaded handler.

Any ideas?

Many thanks again,

Peter

**Comment by JulienItard** [comment]
Same problem here ! :+1:

**Comment by peterbournecommunications** [comment]
Yes - but no solution yet.. I'm looking at other tools - and can't find one that fits the bill! I need: crop / resize / rotate via Canvas... and catering for images that were taken in portrait mode (don't mind having to initially rotate the image - just want to be able to upload that correctly rotated and resized image to a PHP script).

**Comment by scottcheng** [comment]
One approach to this is to add a rotation feature (e.g. by 90 degrees), which sounds feasible and reasonable. If we want to automatically correct the orientation, we need to somehow read that information from image meta data. #75 discusses this specifically.

**Comment by michelerota** [comment]
+1

**Comment by duanmao** [comment]
+1
Has rotation feature been added already?

**Comment by petebarr** [comment]
+1

**Comment by gdelcurla** [comment]
+1 Great Plugin, thanks for all of your hard work. This rotation problem has become an issue for me as well.

**Comment by mauromorello** [comment]
I found somewhere this, I hope someone will be able to insert in this great plugin:
It seems to use a canvas to perform rotation, then put new data in this._image.src and then repaint canvas, but I'm too newbie :frowning: 

	_doRotation: function (degrees){
			var rads=degrees*Math.PI/180;
			var newWidth, newHeight;
			var c = Math.cos(rads);
			var s = Math.sin(rads);
			if (s < 0) { s = -s; }
			if (c < 0) { c = -c; }
			newWidth = this._image.height * s + this._image.width * c;
			newHeight = this._image.height * c + this._image.width * s;
			var canvas = document.createElement('canvas');
			var ctx = canvas.getContext("2d");
			canvas.width = parseInt(newWidth, 10);
			canvas.height = parseInt(newHeight, 10);
			var cx=canvas.width/2;
			var cy=canvas.height/2;
			ctx.clearRect(0, 0, canvas.width, canvas.height);
			ctx.translate(cx, cy);
			ctx.rotate(rads);
			ctx.drawImage(this._image, -this._image.width / 2, -this._image.height / 2);
			this._image.src = canvas.toDataURL("image/png");
			this._paintCanvas();
		}

**Comment by pensierinmusica** [comment]
@scottcheng agree with https://github.com/scottcheng/cropit/issues/92#issuecomment-139840813

I'd say adding a simple optional button that rotates the image 90 degrees clockwise each time it's pressed would solve most cases and be relatively straightforward to implement  :)

Thoughts?

**Comment by clrblnd** [comment]
+1

**Comment by Manmade** [comment]
pensierinmusica.
It rotates as it should(great!), but I can't get it to update the imageData.
Where do I put ctx.rotate(_rotation * Math.PI / 180);? And what is "ctx"  
Has anybody got this to work?

**Comment by pensierinmusica** [comment]
Hi @Manmade, `ctx` in my code example is `canvasContext` in the source code where `getCroppedImageData` is defined: https://github.com/scottcheng/cropit/blob/master/src/cropit.js#L423

The quick code example I posted would work fine if there's no zoom and image offset, otherwise rotation would have to take that into account as well.

I think it'd be nice to have rotation as a standard Cropit feature, which is the purpose of this issue. Any news from @scottcheng? Cheers!

**Comment by jupitercow** [comment]
This does seem fairly simple and a much better option than the EXIF data since this doesn't require another library. @pensierinmusica's code is a good start. I haven't been able to implement the export on my end yet. 

+1 for this getting built in. It is making it really hard to support mobile, and just images from phones in general...

**Comment by pensierinmusica** [comment]
Thanks @scottcheng!  :)
