### ISSUE TITLE
Is it possible to get cropit to 'touch' the file input again after re-enable?

### ISSUE THREAD

**Issue by phunksta** [scottcheng/cropit#95]
Hi,

My basic premise might be off here, but I am admittedly in a rush!

I have a situation where I am sometimes using 'disable' method to turn off cropit so that the form can be used to upload non-image file types.
This works fine, except when cropit is disabled, a image file is chosen, I detect the change and file type as being an image, and then try to use 'reenable' to get cropit functions back.

How can I then get cropit to 'touch' the file input again and pick up the image state from the file chosen BEFORE reenable was called?

Once again, thanks for this great plugin. I have had tens of 'silly' requests from my users around this and ropit has been able to do them all. It is only my own rushing through that has cause dme any problems!

Thanks

**Comment by scottcheng** [comment]
Interesting use case. One thing you can do is to trigger a `change` event on the file input **after** you reenable cropit, so it would load image from the file input again and show in the preview box. When cropit is disabled it does not listen to file input changes.
