### ISSUE TITLE
Small images (~ 50KB and under) are not being loaded

### ISSUE THREAD

**Issue by tgiunipero** [scottcheng/cropit#96]
Noticed this when updating from v0.2.0.  The problem seems to have been introduced between v0.2.0 and v0.3.0.  You can also verify this by attempting an upload on the [demo page](http://scottcheng.github.io/cropit/) (current version is 0.4.1).

**Comment by tgiunipero** [comment]
Here's a demo image (but any jpeg of small filesize can be used).

![1241353](https://cloud.githubusercontent.com/assets/1241353/9406703/3996c272-4803-11e5-847e-01c19f6cc8f5.jpg)

**Comment by CyrilSiman** [comment]
Hi, I'm made some test on the [Demo Page](http://scottcheng.github.io/cropit/) and in fact for me isn't a problem with filesize but with the image size. If you try with the first sample in the demo page : the DIV have dim : width: 448px; height: 448px. If we try to upload an image smaller than 448px it's not loaded, we have to use a bigger image than 448px. 

Try with these images the first one 447px (doesn't work) and the second 449px (works for me)

![447](https://cloud.githubusercontent.com/assets/7025806/9419232/4e644150-485a-11e5-8359-7b1413eb5690.jpg)

![449](https://cloud.githubusercontent.com/assets/7025806/9419237/537ab8b8-485a-11e5-95be-6c6c7e539b15.jpg)
 
I'll will learn if it's possible to detect a too smaller image with event.

**Comment by tgiunipero** [comment]
my bad.  I had a closer look and it seems there is a `smallImage` option which is set to `'reject'` by default (see [documentation](http://scottcheng.github.io/cropit/)).  Setting it to `'stretch'` solved the issue for me.  I'm guessing this option didn't exist for version 0.2.0.

Closing issue...

**Comment by CyrilSiman** [comment]
Maybe it's a good idea to modify the demo page. Because when I've tried the first time I believe that the library doesn't work with png (in fact I've used a too smaller image).

**Comment by tgiunipero** [comment]
...or imho have `smallImage` set to `allow` or `stretch` in the library by default.
