### ISSUE TITLE
onMove callback

### ISSUE THREAD

**Issue by aas395** [scottcheng/cropit#97]
Hey,

First of all, thank you for all your good work! I love this plugin.

I'm trying to create an interface that has an image manipulation area and a non-moveable preview next to it, and I'm having a hard time doing that with this plugin. The easiest way for me to do this would be to have some sort of onMove callback that lets me get access to the current state of the image as it's being moved. Are there any plans to make this available anytime soon?

**Comment by aas395** [comment]
Also hoping for an onZoom callback that's part of the plugin

**Comment by scottcheng** [comment]
Good suggestions. I just added `onOffsetChange` and `onZoomChange` callbacks on the [dev branch](https://github.com/scottcheng/cropit/commits/dev). Feel free to play with it and let me know what you think.

**Comment by kylescousin** [comment]
Thanks for this amazingly useful plugin. I am also missing this one feature.

Is that this version? https://github.com/scottcheng/cropit/blob/dev/dist/jquery.cropit.js

I can't get this to work... I need to be  able to get the position of the image when you drag it around or zoom it. 


onOffsetChanged: function () {
			console.log('test');
		}, - nothing gets logged...

And the following gives an error in this dev branch: var imageSize = $imageCropper.cropit('imageSize'),

Could you please add a callback that we can use to get coordinates when dragging the image around over the page? The reason I need this is that I need to keep a vertical red line centered on the image at all times, so the I need to know where to position the line when the user drags or zooms the image.

Cheers!
